language: cpp
sudo: false
cache:
  directories:
  - container
env:
  matrix:
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
  global:
  - secure: Kyo7jrQf21rN0W7N3HnBCKEDWDTSRoHZmlCnjzAdFNr64O3EVnttrjlumpd63s6iiqomomS3VL3dWvvQTwrQngIyOcOHBc9t7KVbgfwHoWeR6M0rLMnXlAO1bcL7anCchc2cMQV5mQebuZ2z9vrlDcKRJJ1JrnlzKzVUH2s9dW7BDo+BbsD+RNtrt4P4lKhkzl6tPkVrsjBRkNCEv2Ue+oWlQSMTaaMRouEqTsmmECkKSuakkTTnF4dhuoj/6bGEnax436IjQnpQ4VwaasApm6QKgcPoetfL6rI0faA7wq0vqfoClTJMM9ALunuakPRYD8a8NgFJSKmItsBD4Y+lHSuKdxWLU0HmYuu7ir1YcL6QMvJkVT36+nEYvKxqXtXVDAiocztgmcSwmBfn0G4L5S8I7skczILI+JS4Igvj467xm35nvcJdWOLeKocMXfmaredwRDQjA1XevizA4jn8N+nZm/CdFoWgaGnKDoWeBrcztNUPY9eqHIOQ1AsqgYSMeQxY/CrE4E8r4FDxcTSdxtMyS/hNzQCX8mZTGM/6a+8zqbzIDpygVH8L2ZqdfALCTLBrOSKe4y/oA3flFdiRWLwZnCSbKEmQM0BdKHY6Z5TltSutD971mX+ID28qf/10VMhJ8bW57T0wovkl/IO6jvk9TVqw/jDqHNZh44xP2EE=
  - secure: o8TPXfYhn8tWKGWpRDC4A6t+tZRWhoZgMJ+PNu+7AxK/4ohfA2RPCvJoH20+ciZaCpBwWytJ2w6MuImK5lZcZmZQJoDPgygci8RQ65+cjDhOWPu3J9MWgSMCm+7ywWI5MwCly7wjKpFzbWfKLX5pSuuPJfUKFn3Qc1p//OvijZ5ijuDmjDc2UqoResDzQhadTuB3xDz6Cwg/T1xRCA/5Ccj6+o9nXu+Y8vUnxIyYRTjjyYAwGTQoBBNS2rU8zuIwXJOavJTR2sB/6XEKRFhD22/IPWL8a0+wjYfu+Fv+1bSwXcgxVNLydXk5ZLU0yMPTsOcFE5R0hIqotRiVpxxQ0bttUo2QLxImX5lTZr2lmPNIugl63ksO3QXOMqCH3jWPdgp2HHBzvEmxGr0jE5f3Nf5aQQsbY7ysfxk3WFwl9d3aiN0FxJVVQTS9eHCDHoky1CODXEVfqQtloiKj5+qcJTIiO/dpj0ansK9BMVmR3+b0NM0pODn7TbuGbI+KWrzqtwHSERz0krjyXFPkWFizqr86bGivNwKzjmFFkAajP1n4mDDiWrdfQppK7t1DGAM23d04oHJP7nEU225K6lW4BhTJ4D75UWUN7DC8UHNUXrlS5BJcBqtWWu+sOy6r7GfGtPIL2IrPgcdRL5cktZgzaBvhdrebr6PTI8nT7SbdyzQ=
  - secure: ZtjmpmQoYrRY650g0Ngm2YEmi66jQsCrt2KjIJE0iJ7ZlV8JneGFrxFrerpPyPMe0qb/NNBpIQZ+9SJkd9StPFPVCHkfUL7zyvMTkQ+oSszOucon2APhfsU2hSNKkffu0OCRA9M54jL++ZqJsDa6+0/01ZPs8lchrsjrVQJZiUPE3+Mj4XZnQ5yI/ocIcOhdBReAPUDcWZEdWz2rqSRMJVv9HuCGGkUWjftayQoyy8iG1JK9rJxhvNXujEBwBXrfuep4HUjYVLTlp2yk6pqlqo0+Bq8zYqjyZgB4zvVAhID2eKI4O1dg1ORJreYIatucGI6euMBO0i3zoWtm9bL4nX9MBykO3Jg/QoqikDdYNY2x5adNwm4T/bOUSezUZlu+CllxjryFOBNN6wAITneRXS7eT9Ew5n953kOEPyQisG8QCW0Xtoqaq3xjlhrbv+6razqrAxFige7zmBPdXFpVGY51JElk/QYlV5qn8KZUvGZG6SBLLdgzO8uZX6sKZgcGhjz1npajL1bbSnngYVu2Per0idVVcftNzswcc+n+Rt7pn76jQIVAeh3zIcXwMG1rpbNz+RLZCB6Z4VrJVNAOTlehpskMUX0ZSR9C0NTkQYH6sul/mfdsP+Jbdm8rNoyh56sld04/CFme5vh0htcmD55Oy4nBpcvRTKqO2an28dc=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4-dev
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace cmake_module --generator
  "${CMAKE_GENERATOR}"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/conan/before_deploy.py --package="cmake-module-common"
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis-deploy"
  on:
    repo: polysquare/cmake-module-common
    branch: master
    condition: "${DEPLOY} = 1"
