language: cpp
sudo: false
cache:
  directories:
  - container
env:
  matrix:
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
  global:
  - secure: Kyo7jrQf21rN0W7N3HnBCKEDWDTSRoHZmlCnjzAdFNr64O3EVnttrjlumpd63s6iiqomomS3VL3dWvvQTwrQngIyOcOHBc9t7KVbgfwHoWeR6M0rLMnXlAO1bcL7anCchc2cMQV5mQebuZ2z9vrlDcKRJJ1JrnlzKzVUH2s9dW7BDo+BbsD+RNtrt4P4lKhkzl6tPkVrsjBRkNCEv2Ue+oWlQSMTaaMRouEqTsmmECkKSuakkTTnF4dhuoj/6bGEnax436IjQnpQ4VwaasApm6QKgcPoetfL6rI0faA7wq0vqfoClTJMM9ALunuakPRYD8a8NgFJSKmItsBD4Y+lHSuKdxWLU0HmYuu7ir1YcL6QMvJkVT36+nEYvKxqXtXVDAiocztgmcSwmBfn0G4L5S8I7skczILI+JS4Igvj467xm35nvcJdWOLeKocMXfmaredwRDQjA1XevizA4jn8N+nZm/CdFoWgaGnKDoWeBrcztNUPY9eqHIOQ1AsqgYSMeQxY/CrE4E8r4FDxcTSdxtMyS/hNzQCX8mZTGM/6a+8zqbzIDpygVH8L2ZqdfALCTLBrOSKe4y/oA3flFdiRWLwZnCSbKEmQM0BdKHY6Z5TltSutD971mX+ID28qf/10VMhJ8bW57T0wovkl/IO6jvk9TVqw/jDqHNZh44xP2EE=
  - secure: o8TPXfYhn8tWKGWpRDC4A6t+tZRWhoZgMJ+PNu+7AxK/4ohfA2RPCvJoH20+ciZaCpBwWytJ2w6MuImK5lZcZmZQJoDPgygci8RQ65+cjDhOWPu3J9MWgSMCm+7ywWI5MwCly7wjKpFzbWfKLX5pSuuPJfUKFn3Qc1p//OvijZ5ijuDmjDc2UqoResDzQhadTuB3xDz6Cwg/T1xRCA/5Ccj6+o9nXu+Y8vUnxIyYRTjjyYAwGTQoBBNS2rU8zuIwXJOavJTR2sB/6XEKRFhD22/IPWL8a0+wjYfu+Fv+1bSwXcgxVNLydXk5ZLU0yMPTsOcFE5R0hIqotRiVpxxQ0bttUo2QLxImX5lTZr2lmPNIugl63ksO3QXOMqCH3jWPdgp2HHBzvEmxGr0jE5f3Nf5aQQsbY7ysfxk3WFwl9d3aiN0FxJVVQTS9eHCDHoky1CODXEVfqQtloiKj5+qcJTIiO/dpj0ansK9BMVmR3+b0NM0pODn7TbuGbI+KWrzqtwHSERz0krjyXFPkWFizqr86bGivNwKzjmFFkAajP1n4mDDiWrdfQppK7t1DGAM23d04oHJP7nEU225K6lW4BhTJ4D75UWUN7DC8UHNUXrlS5BJcBqtWWu+sOy6r7GfGtPIL2IrPgcdRL5cktZgzaBvhdrebr6PTI8nT7SbdyzQ=
  - secure: O7RWEPQpCZUEHR+3bOMYy7CBVSgwZnsV+e71dMVaPZ70jVFRxgMJ564kYkQXX4KBx18SeikqpcQDtEnNFY1jUO5CfkXydgCJaythvIxXG7Z3Ru5b7EDv06HfGtVDAoYAw4ZPUwz1I7gj6cHBPoMOsDwlT2/TrD3OJhpQHSxZgnn8ojASQIRYLbCKWiPAgqdpoW7ccw4uPrYnMbq6a5JgOUoM5Gkl9wBg9q8YqHcYp9PC9GGFmpnhMotfQCdYGcqVgZrZMN7W9abjeTk2vynnAGO8fqFBBqALl3hAzLhr9JWU1p6v5gyO0dide0w9uFZaYQoJimAajfvK3AzDU5J3AxAbMARj2wqV/TUOpM66rng3CV+3FYiAEZBtaUxYcslGjESs+2mx57C04KzqNVSKNNTZTOY+iwzMj9Zuc65kVwoZqo0UvI2UV/fxPWYgT3SzIW73ZdS9M5h7Ax+9BBOLIZ+BZ80230vL7vEFJR3VkMnDHSFdYNAVUY4zL3hE+QEuEM89O481vPaVewtFW4ZEJojeYWsyXnZRYI9c7LejsQfbHYehD2vIDqt9WHIJyeS0bGr9Y3E2BzIFUjp+lTNKojSwaoQ7PfhqufaCnYip6KDZMiezJZr6CPffu5waG/IjEidCla6HE/sz6M21XJPQo9JJNcOuQFLmBUFGFsQPRBM=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4-dev
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
- container/_languages/python/3.4.4/bin/conan install --build=missing -u cmake-linter-cmake/master@smspillaz/cmake-linter-cmake
- container/_languages/python/3.4.4/bin/conan install --build=missing -u style-linter-cmake/master@smspillaz/style-linter-cmake
- container/_languages/python/3.4.4/bin/conan install --build=missing -u cmake-unit/master@smspillaz/cmake-unit
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace cmake_module --generator
  "${CMAKE_GENERATOR}"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/conan/before_deploy.py --package="cmake-module-common"
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis-deploy"
  on:
    repo: polysquare/cmake-module-common
    branch: master
    condition: "${DEPLOY} = 1"
